version: "3.9"

services:

  totum:
    container_name: ttm-totum
    image: totumonline/totum-mit:2.4.42
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_fpm_conf/totum_fpm.conf:/etc/php/8.0/fpm/pool.d/totum.conf
      - ./nginx_fpm_conf/totum_nginx${SSLON}.conf:/etc/nginx/sites-available/totum.online.conf

      - ./cron/totum_cron:/var/www/cron/totum_cron

      - ./totum/Conf.php:/var/www/totum-mit/Conf.php
      - ./totum/fls:/var/www/totum-mit/http/fls
      - ./totum/totumTmpfiles:/var/www/totum-mit/totumTmpfiles
      - ./totum/myLogs:/var/www/totum-mit/myLogs
      - ./totum/backups:/var/www/totum-mit/backups

      - ./certbot/etc_letsencrypt:/etc/letsencrypt
      - ./certbot/log:/var/log/letsencrypt
      - ./certbot/var_lib:/var/lib/letsencrypt

    environment:
      TZ: ${TOTUMTIMEZONE}

    depends_on:
      - postgres
      - exim
    
    restart: always

  postgres:
    container_name: ttm-postgres
    image: postgres:14.1-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data/pgdata

    environment:
      POSTGRES_USER: totum
      POSTGRES_PASSWORD: ${TOTUMBASEPASS}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TOTUMTIMEZONE}
      PGTZ: ${TOTUMTIMEZONE}
    
    restart: always

  exim:
    container_name: ttm-smtp
    image: totumonline/ttm-smtp:1.0
    volumes:
      - ./dkim/config:/etc/exim4/_docker_additional_macros
      - ./dkim/domain.key:/etc/exim4/domain.key
      - ./exim_log:/var/log/exim4

    environment:
      DISABLE_IPV6: true
      TZ: ${TOTUMTIMEZONE}
    
    restart: always
  